CREATE TABLE "public"."Boards" (
    "Id" uuid NOT NULL DEFAULT uuidv7(),
    "OwnerUserId" uuid NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Picture" bytea,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Boards_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId")
        REFERENCES "public"."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Boards_OwnerUserId" ON "public"."Boards" ("OwnerUserId");

CREATE TABLE "public"."BoardEntryStates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0),
    "Name" character varying(16) NOT NULL,
    CONSTRAINT "PK_BoardEntryStates" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_BoardEntryStates_Name"
    ON "public"."BoardEntryStates" ("Name");

INSERT INTO "public"."BoardEntryStates" ("Name")
VALUES ('todo'), ('in-progress'), ('completed'), ('dnf');

CREATE TABLE "public"."BoardEntries" (
    "BoardId" uuid NOT NULL,
    "GameId" bigint NOT NULL,
    "StateId" integer NOT NULL DEFAULT 0,
    "AddedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_BoardEntries" PRIMARY KEY ("BoardId", "GameId"),
    CONSTRAINT "FK_BoardEntries_Boards_BoardId" FOREIGN KEY ("BoardId")
        REFERENCES "public"."Boards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BoardEntries_Games_GameId" FOREIGN KEY ("GameId")
        REFERENCES "public"."Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BoardEntries_BoardEntryStates_StateId" FOREIGN KEY ("StateId")
        REFERENCES "public"."BoardEntryStates" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_BoardEntries_GameId" ON "public"."BoardEntries" ("GameId");
CREATE INDEX "IX_BoardEntries_StateId" ON "public"."BoardEntries" ("StateId");
