CREATE TABLE "public"."BoardEntryStates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0),
    "Name" character varying(16) NOT NULL,
    CONSTRAINT "PK_BoardEntryStates" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_BoardEntryStates_Name"
    ON "public"."BoardEntryStates" ("Name");

INSERT INTO "public"."BoardEntryStates" ("Name")
VALUES ('todo'), ('in-progress'), ('completed'), ('dnf');

ALTER TABLE "public"."BoardEntries"
    DROP CONSTRAINT "CK_BoardEntries_State";

ALTER TABLE "public"."BoardEntries"
    ALTER COLUMN "State" DROP DEFAULT,
    ALTER COLUMN "State" TYPE integer
        USING CASE "State"
            WHEN 'Todo' THEN 0
            WHEN 'InProgress' THEN 1
            WHEN 'Completed' THEN 2
            WHEN 'Dnf' THEN 3
        END,
    ALTER COLUMN "State" SET DEFAULT 0;

ALTER TABLE "public"."BoardEntries"
    RENAME COLUMN "State" TO "StateId";

ALTER TABLE "public"."BoardEntries"
    ADD CONSTRAINT "FK_BoardEntries_BoardEntryStates_StateId"
        FOREIGN KEY ("StateId") REFERENCES "public"."BoardEntryStates" ("Id") ON DELETE RESTRICT;

CREATE INDEX "IX_BoardEntries_StateId" ON "public"."BoardEntries" ("StateId");
